insert into collection (collection_id, name) values (1, 'Open Access Research');
insert into handle (handle_id, handle, resource_type_id, resource_id) values (1,'1885/2',3,1);

insert into collection (collection_id, name) values (4, 'Open Access Digital Theses');
insert into handle (handle_id, handle, resource_type_id, resource_id) values (3,'1885/4',3,4);

insert into item(item_id, submitter_id, in_archive, withdrawn, last_modified, owning_collection) values(1,1,1,0,'2015-07-23 11:21:31',1);
insert into handle (handle_id, handle, resource_type_id, resource_id) values (2,'1885/3',2,1);

insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (1,1,110,'u1111111xPUB2',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (2,1,27,'Journal abstract example',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (3,1,55,'Journal of all',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (4,1,143,'57',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (5,1,39,'Elsevier',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (6,1,146,'861503',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (7,1,146,'970102',null,2,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (8,1,3,'Body, Some',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (9,1,3,'Turner, Genevieve',null,2,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (10,1,3,'Person, Random',null,3,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (11,1,3,'Khanna, Rahul',null,4,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (12,1,66,'Journal Article',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (13,1,144,'59',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (14,1,109,'020102',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (15,1,109,'030303',null,2,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (16,1,109,'040106',null,3,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (17,1,120,'E1111',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (18,1,120,'u1111111',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (19,1,120,'E1112',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (20,1,120,'u1111112',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (21,1,142,'21',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (22,1,64,'Test Journal Title',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (23,1,56,'http://google.com.au',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (24,1,21,'1234-5678',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (25,1,107,'2015-09-21',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (26,1,145,'10.12345/6789',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (27,1,121,'Body, Some, UNSW',null,1,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (28,1,121,'Turner, Genevieve, ITS, ANU',null,2,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (29,1,121,'Person, Random, UTAS',null,3,null,-1);
insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (30,1,121,'Khanna, Rahul, ITS, ANU',null,4,null,-1);
--insert into metadatavalue (metadata_value_id, item_id, metadata_field_id, text_value, text_lang, place, authority, confidence) values (,,,,,,null,-1);
